# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/gui_pybombs.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(652, 464)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setStyleSheet("alternate-background-color: rgb(211, 215, 207);")
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 652, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuActions = QtWidgets.QMenu(self.menubar)
        self.menuActions.setObjectName("menuActions")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setStyleSheet("")
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_About_GNU_Radio = QtWidgets.QAction(MainWindow)
        self.action_About_GNU_Radio.setObjectName("action_About_GNU_Radio")
        self.action_About_CGRAN = QtWidgets.QAction(MainWindow)
        self.action_About_CGRAN.setObjectName("action_About_CGRAN")
        self.action_Apply = QtWidgets.QAction(MainWindow)
        self.action_Apply.setEnabled(False)
        font = QtGui.QFont()
        self.action_Apply.setFont(font)
        self.action_Apply.setIconVisibleInMenu(False)
        self.action_Apply.setObjectName("action_Apply")
        self.action_Refresh = QtWidgets.QAction(MainWindow)
        self.action_Refresh.setIconVisibleInMenu(False)
        self.action_Refresh.setObjectName("action_Refresh")
        self.action_Search = QtWidgets.QAction(MainWindow)
        self.action_Search.setIconVisibleInMenu(False)
        self.action_Search.setObjectName("action_Search")
        self.actionConfig_Preferences = QtWidgets.QAction(MainWindow)
        self.actionConfig_Preferences.setObjectName("actionConfig_Preferences")
        self.action_Preferences = QtWidgets.QAction(MainWindow)
        self.action_Preferences.setIconVisibleInMenu(False)
        self.action_Preferences.setObjectName("action_Preferences")
        self.action_RunningConfig = QtWidgets.QAction(MainWindow)
        self.action_RunningConfig.setObjectName("action_RunningConfig")
        self.action_About_PyBOMBS = QtWidgets.QAction(MainWindow)
        self.action_About_PyBOMBS.setObjectName("action_About_PyBOMBS")
        self.action_Discard_Changes = QtWidgets.QAction(MainWindow)
        self.action_Discard_Changes.setObjectName("action_Discard_Changes")
        self.menuFile.addAction(self.action_Preferences)
        self.menuFile.addAction(self.action_RunningConfig)
        self.menuActions.addSeparator()
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.action_Apply)
        self.menuActions.addAction(self.action_Discard_Changes)
        self.menuActions.addAction(self.action_Refresh)
        self.menuActions.addSeparator()
        self.menuActions.addSeparator()
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.action_Search)
        self.menuHelp.addAction(self.action_About_PyBOMBS)
        self.menuHelp.addAction(self.action_About_GNU_Radio)
        self.menuHelp.addSeparator()
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.action_About_CGRAN)
        self.menuHelp.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.action_Apply)
        self.toolBar.addAction(self.action_Discard_Changes)
        self.toolBar.addAction(self.action_Refresh)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Preferences)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_Search)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuActions.setTitle(_translate("MainWindow", "Actions"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_About_GNU_Radio.setText(_translate("MainWindow", "&About GNU Radio"))
        self.action_About_CGRAN.setText(_translate("MainWindow", "&About CGRAN"))
        self.action_Apply.setText(_translate("MainWindow", "&Apply Changes"))
        self.action_Refresh.setText(_translate("MainWindow", "&Refresh List"))
        self.action_Search.setText(_translate("MainWindow", "&Search"))
        self.action_Search.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actionConfig_Preferences.setText(_translate("MainWindow", "&Config Preferences"))
        self.action_Preferences.setText(_translate("MainWindow", "&Preferences"))
        self.action_RunningConfig.setText(_translate("MainWindow", "&Running Config"))
        self.action_About_PyBOMBS.setText(_translate("MainWindow", "&About PyBOMBS"))
        self.action_Discard_Changes.setText(_translate("MainWindow", "&Discard Changes"))

import myicons_rc
